### ISSUE TITLE
HTTP error code 408

### ISSUE THREAD

**Issue by espiegel** [mixpanel/mixpanel-java#15] opened 2015-02-03 15:57 UTC
I'm getting a bunch of these errors every once in a while:

Server returned HTTP response code: 408 for URL: http://api.mixpanel.com/track?ip=0 

After I perform: mixPanelApi.deliver(delivery)

I'm just wondering if anyone else encountered this issue

**Comment by chook** [comment] 2015-02-03 17:53
#14 also speaks about this.

**Comment by joeatwork** [comment] 2015-02-03 18:01
I'm going to close this as a duplicate of #14 - @espiegel , I'm going to tag you in that issue so that you can follow progress there.

**Closed by joeatwork** 2015-02-03 18:01 UTC
Labels: bug
